# Form implementation generated from reading ui file 'dlgCambioProp.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCambioProp(object):
    def setupUi(self, dlgCambioProp):
        dlgCambioProp.setObjectName("dlgCambioProp")
        dlgCambioProp.resize(300, 200)
        dlgCambioProp.setMinimumSize(QtCore.QSize(300, 200))
        dlgCambioProp.setMaximumSize(QtCore.QSize(300, 200))
        dlgCambioProp.setModal(True)
        self.lblExportar = QtWidgets.QLabel(dlgCambioProp)
        self.lblExportar.setGeometry(QtCore.QRect(20, 90, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblExportar.setFont(font)
        self.lblExportar.setObjectName("lblExportar")
        self.lblImgexportar = QtWidgets.QLabel(dlgCambioProp)
        self.lblImgexportar.setGeometry(QtCore.QRect(110, 20, 71, 71))
        self.lblImgexportar.setText("")
        self.lblImgexportar.setPixmap(QtGui.QPixmap("img/pregunta.png"))
        self.lblImgexportar.setScaledContents(True)
        self.lblImgexportar.setObjectName("lblImgexportar")
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgCambioProp)
        self.buttonBox.setGeometry(QtCore.QRect(60, 130, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(dlgCambioProp)
        QtCore.QMetaObject.connectSlotsByName(dlgCambioProp)

    def retranslateUi(self, dlgCambioProp):
        _translate = QtCore.QCoreApplication.translate
        dlgCambioProp.setWindowTitle(_translate("dlgCambioProp", "Cambio de propietario"))
        self.lblExportar.setText(_translate("dlgCambioProp", "Quiere cambiar de propietario el coche ?"))
