# Form implementation generated from reading ui file 'dlgExportar.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgExportar(object):
    def setupUi(self, dlgExportar):
        dlgExportar.setObjectName("dlgExportar")
        dlgExportar.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgExportar.resize(300, 200)
        dlgExportar.setMinimumSize(QtCore.QSize(300, 200))
        dlgExportar.setMaximumSize(QtCore.QSize(300, 200))
        dlgExportar.setModal(True)
        self.lblImgexportar = QtWidgets.QLabel(dlgExportar)
        self.lblImgexportar.setGeometry(QtCore.QRect(120, 10, 61, 61))
        self.lblImgexportar.setText("")
        self.lblImgexportar.setPixmap(QtGui.QPixmap("img/pregunta.png"))
        self.lblImgexportar.setScaledContents(True)
        self.lblImgexportar.setObjectName("lblImgexportar")
        self.lblExportar = QtWidgets.QLabel(dlgExportar)
        self.lblExportar.setGeometry(QtCore.QRect(80, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblExportar.setFont(font)
        self.lblExportar.setObjectName("lblExportar")
        self.chkClientes = QtWidgets.QCheckBox(dlgExportar)
        self.chkClientes.setGeometry(QtCore.QRect(80, 110, 70, 17))
        self.chkClientes.setObjectName("chkClientes")
        self.chkCoches = QtWidgets.QCheckBox(dlgExportar)
        self.chkCoches.setGeometry(QtCore.QRect(150, 110, 70, 17))
        self.chkCoches.setObjectName("chkCoches")
        self.btnExportar = QtWidgets.QPushButton(dlgExportar)
        self.btnExportar.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.btnExportar.setObjectName("btnExportar")
        self.btnCancelar = QtWidgets.QPushButton(dlgExportar)
        self.btnCancelar.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(dlgExportar)
        QtCore.QMetaObject.connectSlotsByName(dlgExportar)

    def retranslateUi(self, dlgExportar):
        _translate = QtCore.QCoreApplication.translate
        dlgExportar.setWindowTitle(_translate("dlgExportar", "Exportar"))
        self.lblExportar.setText(_translate("dlgExportar", "Que desea exportar?"))
        self.chkClientes.setText(_translate("dlgExportar", "Clientes"))
        self.chkCoches.setText(_translate("dlgExportar", "Coches"))
        self.btnExportar.setText(_translate("dlgExportar", "Exportar"))
        self.btnCancelar.setText(_translate("dlgExportar", "Cancelar"))
